FROM ubuntu:noble
ENV DEBIAN_FRONTEND noninteractive
RUN apt update ; \
    apt install --yes cmake libblas-dev libblas64-dev liblapack-dev liblapack64-dev git;\
    apt install --yes build-essential;\
    apt install --yes gfortran clang flang  ninja-build debhelper

